// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TabelGPWebAPI;

namespace TabelGPWebAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TabelGPWebAPI.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DateReport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Machine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumSmenReport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PersentOfReport")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("TabelGPWebAPI.Models.Smena", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("DateSmen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumSmen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Smens");
                });

            modelBuilder.Entity("TabelGPWebAPI.Models.WorkUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountDonePieces")
                        .HasColumnType("int");

                    b.Property<string>("EndWorkTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupDifficulty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StartWorkTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeWork")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("WorkUnits");
                });

            modelBuilder.Entity("TabelGPWebAPI.Models.WorkerData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableNum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkerDatas");
                });

            modelBuilder.Entity("TabelGPWebAPI.Models.WorkerReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TbNum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("WorkerReport");
                });

            modelBuilder.Entity("TabelGPWebAPI.Models.WorkerTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<float>("DoubleTime")
                        .HasColumnType("real");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("NightTime")
                        .HasColumnType("real");

                    b.Property<float>("PprTime")
                        .HasColumnType("real");

                    b.Property<float>("PrikTime")
                        .HasColumnType("real");

                    b.Property<float>("ProstTime")
                        .HasColumnType("real");

                    b.Property<float>("SdelTime")
                        .HasColumnType("real");

                    b.Property<Guid>("SmenaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("SrednTime")
                        .HasColumnType("real");

                    b.Property<string>("TbNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SmenaId");

                    b.ToTable("WorkerTimes");
                });

            modelBuilder.Entity("TabelGPWebAPI.Norma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GroupDiff")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Norms");
                });

            modelBuilder.Entity("TabelGPWebAPI.Models.WorkUnit", b =>
                {
                    b.HasOne("TabelGPWebAPI.Models.Report", "Report")
                        .WithMany("WorkUnits")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TabelGPWebAPI.Models.WorkerReport", b =>
                {
                    b.HasOne("TabelGPWebAPI.Models.Report", "Report")
                        .WithMany("WorkerListReports")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TabelGPWebAPI.Models.WorkerTime", b =>
                {
                    b.HasOne("TabelGPWebAPI.Models.Smena", "Smena")
                        .WithMany("WorkerTimes")
                        .HasForeignKey("SmenaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
